// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1.proto

package gateway_rpc_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuildRequest struct {
	//    Build User
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	//    Build Name
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildRequest) Reset()         { *m = BuildRequest{} }
func (m *BuildRequest) String() string { return proto.CompactTextString(m) }
func (*BuildRequest) ProtoMessage()    {}
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{0}
}

func (m *BuildRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildRequest.Unmarshal(m, b)
}
func (m *BuildRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildRequest.Marshal(b, m, deterministic)
}
func (m *BuildRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildRequest.Merge(m, src)
}
func (m *BuildRequest) XXX_Size() int {
	return xxx_messageInfo_BuildRequest.Size(m)
}
func (m *BuildRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildRequest proto.InternalMessageInfo

func (m *BuildRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BuildRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// JobDetail
// Job Detail Info
type JobDetail struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp            string   `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Branch               string   `protobuf:"bytes,4,opt,name=branch,proto3" json:"branch,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Id                   int32    `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobDetail) Reset()         { *m = JobDetail{} }
func (m *JobDetail) String() string { return proto.CompactTextString(m) }
func (*JobDetail) ProtoMessage()    {}
func (*JobDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{1}
}

func (m *JobDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobDetail.Unmarshal(m, b)
}
func (m *JobDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobDetail.Marshal(b, m, deterministic)
}
func (m *JobDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobDetail.Merge(m, src)
}
func (m *JobDetail) XXX_Size() int {
	return xxx_messageInfo_JobDetail.Size(m)
}
func (m *JobDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_JobDetail.DiscardUnknown(m)
}

var xxx_messageInfo_JobDetail proto.InternalMessageInfo

func (m *JobDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *JobDetail) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *JobDetail) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *JobDetail) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *JobDetail) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *JobDetail) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type JobInfo struct {
	Count                int32        `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Jd                   []*JobDetail `protobuf:"bytes,2,rep,name=jd,proto3" json:"jd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *JobInfo) Reset()         { *m = JobInfo{} }
func (m *JobInfo) String() string { return proto.CompactTextString(m) }
func (*JobInfo) ProtoMessage()    {}
func (*JobInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e4aa7d76fd7ee8a, []int{2}
}

func (m *JobInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobInfo.Unmarshal(m, b)
}
func (m *JobInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobInfo.Marshal(b, m, deterministic)
}
func (m *JobInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobInfo.Merge(m, src)
}
func (m *JobInfo) XXX_Size() int {
	return xxx_messageInfo_JobInfo.Size(m)
}
func (m *JobInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_JobInfo.DiscardUnknown(m)
}

var xxx_messageInfo_JobInfo proto.InternalMessageInfo

func (m *JobInfo) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *JobInfo) GetJd() []*JobDetail {
	if m != nil {
		return m.Jd
	}
	return nil
}

func init() {
	proto.RegisterType((*BuildRequest)(nil), "BuildRequest")
	proto.RegisterType((*JobDetail)(nil), "JobDetail")
	proto.RegisterType((*JobInfo)(nil), "JobInfo")
}

func init() { proto.RegisterFile("v1.proto", fileDescriptor_2e4aa7d76fd7ee8a) }

var fileDescriptor_2e4aa7d76fd7ee8a = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xcd, 0xa6, 0x89, 0xc9, 0xa8, 0xa5, 0x0c, 0x22, 0x4b, 0xf1, 0x50, 0x02, 0x42, 0x4f,
	0x0b, 0x6d, 0xc1, 0x8b, 0xb7, 0x22, 0x14, 0x7b, 0xdc, 0x8b, 0xe0, 0x6d, 0x93, 0xac, 0x9a, 0x92,
	0x64, 0x63, 0x32, 0x5b, 0xe9, 0xaf, 0xf0, 0x2f, 0x4b, 0xb6, 0xa1, 0xed, 0xed, 0xbd, 0x6f, 0xe7,
	0xed, 0x0c, 0x0f, 0xa2, 0xfd, 0x42, 0x34, 0xad, 0x21, 0x93, 0x3c, 0xc3, 0xed, 0xda, 0x16, 0x65,
	0x2e, 0xf5, 0x8f, 0xd5, 0x1d, 0x21, 0xc2, 0xc8, 0x76, 0xba, 0xe5, 0xde, 0xcc, 0x9b, 0xc7, 0xd2,
	0xe9, 0x9e, 0xd5, 0xaa, 0xd2, 0x9c, 0x1d, 0x59, 0xaf, 0x93, 0x3f, 0x0f, 0xe2, 0xad, 0x49, 0x5f,
	0x35, 0xa9, 0xa2, 0x3c, 0x4d, 0x78, 0xe7, 0x09, 0x7c, 0x80, 0xb0, 0x23, 0x45, 0xb6, 0x73, 0xb9,
	0x40, 0x0e, 0x0e, 0x1f, 0x21, 0xa6, 0xa2, 0xd2, 0x1d, 0xa9, 0xaa, 0xe1, 0xbe, 0x0b, 0x9c, 0x41,
	0x9f, 0x4a, 0x5b, 0x55, 0x67, 0xdf, 0x7c, 0xe4, 0x9e, 0x06, 0x87, 0x13, 0xf0, 0x6d, 0x5b, 0xf2,
	0xc0, 0xc1, 0x5e, 0xe2, 0x18, 0x58, 0x91, 0xf3, 0xd0, 0xfd, 0xcd, 0x8a, 0x3c, 0x79, 0x81, 0xeb,
	0xad, 0x49, 0xdf, 0xea, 0x4f, 0x83, 0xf7, 0x10, 0x64, 0xc6, 0xd6, 0xe4, 0xee, 0x09, 0xe4, 0xd1,
	0xe0, 0x14, 0xd8, 0x2e, 0xe7, 0x6c, 0xe6, 0xcf, 0x6f, 0x96, 0x20, 0x4e, 0xc7, 0x4b, 0xb6, 0xcb,
	0x97, 0x2b, 0x80, 0x8d, 0x22, 0xfd, 0xae, 0x0e, 0xb2, 0xc9, 0xf0, 0x09, 0xa2, 0x8d, 0x26, 0xd7,
	0x0b, 0xde, 0x89, 0xcb, 0x7e, 0xa6, 0x91, 0x18, 0x96, 0x24, 0x57, 0xeb, 0xc9, 0xc7, 0xf8, 0x4b,
	0x91, 0xfe, 0x55, 0x07, 0xd1, 0x36, 0x99, 0xd8, 0x2f, 0xd2, 0xd0, 0x95, 0xba, 0xfa, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0xb1, 0x36, 0x83, 0x59, 0x60, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GateWayRpcClient is the client API for GateWayRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GateWayRpcClient interface {
	//    GetBuild Query User's All Builds
	GetBuild(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*JobInfo, error)
}

type gateWayRpcClient struct {
	cc *grpc.ClientConn
}

func NewGateWayRpcClient(cc *grpc.ClientConn) GateWayRpcClient {
	return &gateWayRpcClient{cc}
}

func (c *gateWayRpcClient) GetBuild(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*JobInfo, error) {
	out := new(JobInfo)
	err := c.cc.Invoke(ctx, "/GateWayRpc/GetBuild", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateWayRpcServer is the server API for GateWayRpc service.
type GateWayRpcServer interface {
	//    GetBuild Query User's All Builds
	GetBuild(context.Context, *BuildRequest) (*JobInfo, error)
}

// UnimplementedGateWayRpcServer can be embedded to have forward compatible implementations.
type UnimplementedGateWayRpcServer struct {
}

func (*UnimplementedGateWayRpcServer) GetBuild(ctx context.Context, req *BuildRequest) (*JobInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuild not implemented")
}

func RegisterGateWayRpcServer(s *grpc.Server, srv GateWayRpcServer) {
	s.RegisterService(&_GateWayRpc_serviceDesc, srv)
}

func _GateWayRpc_GetBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateWayRpcServer).GetBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GateWayRpc/GetBuild",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateWayRpcServer).GetBuild(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GateWayRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GateWayRpc",
	HandlerType: (*GateWayRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBuild",
			Handler:    _GateWayRpc_GetBuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1.proto",
}
