language: go

go:
  - 1.13.1

env:
  global:
  - GO111MODULE=on
  - NTCI_VERSION=v0.1.0
  - NTCI_IMG_NAME=vikings/ntci

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin

install:
  - go build -o bin/ntci ci-agent/main.go

after_script:
  - docker build -t ${NTCI_IMG_NAME}:${NTCI_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.ntci .
  - docker push ${NTCI_IMG_NAME}:${NTCI_VERSION}-${TRAVIS_BRANCH}