language: go

go:
  - 1.13.1

env:
  global:
    - GO111MODULE=on
    - NTCI_VERSION=v0.1.0
    - NTCI_IMG_NAME=vikings/ntci
    - NTCI_IMG_K8S=vikings/k8s-build
    - NTCI_IMG_DEPLOY=vikings/ntci-deployer

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin

install:
  - go build -o bin/ntci ci-agent/main.go
  - CGO_ENABLED=0 go build -o bin/k8s-build-server ci-build/k8s/*.go
  - go build -o bin/ntci-builder ci-builder/*.go
  - go build -o bin/ntci-deployer-systemd ci-deployer/systemd/*.go

after_script:
  - docker build -t ${NTCI_IMG_NAME}:${NTCI_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.ntci .
  - docker build -t ${NTCI_IMG_K8S}:${NTCI_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.k8s-build .
  - docker build -t ${NTCI_IMG_NAME}-go:latest -f script/builder/golang/Dockerfile.latest .
  - docker build -t ${NTCI_IMG_NAME}-node:yarn -f script/builder/node/Dockerfile.yarn .
  - docker build -t ${NTCI_IMG_DEPLOY}:systemd-latest -f Dockerfile.deploy-systemd .
  - docker push ${NTCI_IMG_NAME}:${NTCI_VERSION}-${TRAVIS_BRANCH}
  - docker push ${NTCI_IMG_K8S}:${NTCI_VERSION}-${TRAVIS_BRANCH}
  - docker push ${NTCI_IMG_NAME}-go:latest
  - docker push ${NTCI_IMG_DEPLOY}:systemd-latest
  - docker push ${NTCI_IMG_NAME}-node:yarn