language: go

go:
  - 1.13.1

env:
  global:
    - GO111MODULE=on
    - NTCI_VERSION=v0.2.1
    - NTCI_IMG_NAME=vikings/ntci
    - NTCI_IMG_K8S=vikings/k8s-build
    - NTCI_IMG_DEPLOY=vikings/ntci-deployer

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_USER" --password-stdin

install:
  - go build -mod=vendor -o bin/ntci ci-agent/*.go
  - CGO_ENABLED=0 go build -mod=vendor -o bin/k8s-build-server ci-build/k8s/*.go
  - go build -mod=vendor -o bin/ntci-builder ci-builder/*.go
  - go build -mod=vendor -o bin/ntci-deployer-systemd ci-deployer/systemd/*.go
  - go build -mod=vendor -o bin/ntci-deployer-k8s ci-deployer/k8s/*.go

after_script:
  - docker build -t ${NTCI_IMG_NAME}:${NTCI_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.ntci .
  - docker push ${NTCI_IMG_NAME}:${NTCI_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${NTCI_IMG_K8S}:${NTCI_VERSION}-${TRAVIS_BRANCH} -f Dockerfile.k8s-build .
  - docker push ${NTCI_IMG_K8S}:${NTCI_VERSION}-${TRAVIS_BRANCH}
  - docker build -t ${NTCI_IMG_NAME}-generic:ubuntu -f script/builder/generic/Dockerfile.ubuntu .
  - docker push ${NTCI_IMG_NAME}-generic:ubuntu
  - docker build -t ${NTCI_IMG_NAME}-go:latest -f script/builder/golang/Dockerfile.latest .
  - docker push ${NTCI_IMG_NAME}-go:latest
  - docker build -t ${NTCI_IMG_NAME}-node:yarn -f script/builder/node/Dockerfile.yarn .
  - docker push ${NTCI_IMG_NAME}-node:yarn
  - docker build -t ${NTCI_IMG_NAME}-java:maven-3-jdk-8 -f script/builder/java/Dockerfile.maven.3.jdk.8 .
  - docker push ${NTCI_IMG_NAME}-java:maven-3-jdk-8
  - docker build -t ${NTCI_IMG_DEPLOY}:systemd-latest -f Dockerfile.deploy-systemd .
  - docker push ${NTCI_IMG_DEPLOY}:systemd-latest
  - docker build -t ${NTCI_IMG_DEPLOY}:k8s-latest -f Dockerfile.deploy-k8s .
  - docker push ${NTCI_IMG_DEPLOY}:k8s-latest